version: '3.7'

services:
  server:
    build:
      context: ./server/
      dockerfile: dockerfile
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_HOST: "mysql-server"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    ports:
      - 3002:3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 3s
      retries: 3
    depends_on:
      - mysql-server
    restart: on-failure
  
  mysql-server:
    build: ./db/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always
